[package]
name = "sample"
version = "0.1.0"
authors = ["ohkubo kohei <kuboon@trick-with.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3"
num-traits = "0.2.14"

